{% set name = "spectrafit" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/SpectraFit-{{ version }}.tar.gz
  sha256: b387c6492c4d6165cb6e8b092ef230d2e4978a906f60535f37e61225675bb224

build:
  number: 0
  noarch: python
  entry_points:
    - spectrafit = spectrafit.spectrafit:command_line_runner
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<3.10
  run:
    - corner >=2.2.1,<3.0.0
    - dill >=0.3.4,<0.4.0
    - emcee >=3.1.1,<4.0.0
    - lmfit >=1.0.2,<2.0.0
    - matplotlib-base >=3.4.2,<4.0.0
    - numdifftools >=0.9.40,<0.10.0
    - numpy >=1.21.1,<2.0.0
    - openpyxl >=3.0.7,<4.0.0
    - pandas >=1.3.0,<2.0.0
    - python >=3.6,<3.10
    - pyyaml >=6.0.0,<7.0.0
    - scipy >=1.7.0,<2.0.0
    - seaborn >=0.11.1,<0.12.0
    - statsmodels >=0.13.1,<0.14.0
    - tabulate >=0.8.9,<0.9.0
    - toml >=0.10.2,<0.11.0
    - tqdm >=4.62.3,<5.0.0

test:
  imports:
    - spectrafit
    - spectrafit.test
  commands:
    - pip check
    - spectrafit --help
  requires:
    - pip

about:
  home: https://pypi.org/project/spectrafit/
  summary: Fast fitting of 2D-Spectra with established routines
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    SpectraFit is a command-line tool for quick data fitting based on the regular expression of distribution functions.
  doc_url: https://anselmoo.github.io/spectrafit/
  dev_url: https://github.com/Anselmoo/spectrafit/

extra:
  recipe-maintainers:
    - Anselmoo
