{% set name = "keras-nlp" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/keras-nlp-{{ version }}.tar.gz
  sha256: 44723deed5c271078cae48ca91cf8e8f6c9ffe85e01a52aee17d02366de959a5

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - absl-py
    - numpy
    - packaging
    - tensorflow  # [not osx]

test:
  imports:
    - examples
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://keras.io/examples/nlp/
  summary: Industry-strength Natural Language Processing extensions for Keras.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/keras-team/keras-nlp
  doc_url: https://keras.io/examples/nlp/

extra:
  recipe-maintainers:
    - Anselmoo
