{% set name = "pytest-cov" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-cov-{{ version }}.tar.gz
  sha256: 996b79efde6433cdbd0088872dbc5fb3ed7fe1578b68cdbba634f14bb8dd0470

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - coverage >=5.2.1
    - pytest >=4.6
    - python >=3.6

test:
  imports:
    - pytest_cov
  commands:
    - pytest --cov -h

about:
  home: https://pypi.org/project/pytest-cov/
  doc_url: https://pytest-cov.readthedocs.io/
  dev_url: https://github.com/pytest-dev/pytest-cov
  summary: Pytest plugin for measuring coverage.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Anselmoo
